### ISSUE TITLE
[ASK] wuih keren, kuliah di binus.

### ISSUE THREAD

**Issue by dzakki** [satyakresna/boltika#1]
btw mas satyakrensa kuliah dibinus dapat beasiswa kah? atau reguler? jika reguler butuh biaya berapa yaa? rencana mau S1 disana juga.

**Comment by satyakresna** [comment]
Halo @dzakki, waktu saya memutuskan kuliah di Binus Online Learning saya mengikuti Tes Potensi Keberhasilan Studi dan entah bagaimana saya masuk dalam suatu peringkat yang mana saya diberikan potongan 4 juta rupiah untuk pembayaran biaya semester I. Sehingga, di semester I yang semula saya bayar 12,9 juta menjadi 8,9 juta. Untuk biaya dari saya jenjang D3 - S1 Teknik Informatika yang saya hitung (bisa berubah-ubah tergantung kebijakan Binus) seperti tabel di bawah.

| Semester | Jumlah Mata Kuliah | Biaya     | BP3       | DP3       | Skripsi   | Total      |
|----------|--------------------|-----------|-----------|-----------|-----------|------------|
| 1        |                  5 | 6.750.000 | 2.200.000 | 4.000.000 |         0 | 12.950.000 |
| 2        |                  5 | 6.750.000 | 2.200.000 |         0 |         0 |  8.950.000 |
| 3        |                  6 | 8.100.000 | 2.200.000 |         0 |         0 | 10.300.000 |
| 4        |                  3 | 4.050.000 | 2.200.000 |         0 | 4.000.000 | 10.250.000 |
| #        | #                  | #         | #         | #         | #         | 42.450.000 |

1 mata kuliah waktu itu tahun 2021 sekitar 1.350.000

Detil biaya kuliah bisa dicek di sini: https://onlinelearning.binus.ac.id/biaya-kuliah/.

Kalo misalnya tertarik ikut kuliah di Binus Online Learning dan ingin ikut tes pendaftarannya, saya ada buat semacam notifikasi via email untuk ngasih tahu jadwal pendaftaran Binus Online Learning (Jakarta) dibuka, websitenya: https://jadwalbinusonline.com/

**Comment by dzakki** [comment]
halo mas @satyakresna, wah jawabanya detail bangettt. semoga lancar kuliahnya disana ya mas.

https://jadwalbinusonline.com/ useful banget nih, buat diriku. Terimakasih banyak mas.

**Comment by satyakresna** [comment]
Sama” @dzakki. Semoga lancar.
